import type { Category, Transaction } from '@/types';

export const MOCK_CATEGORIES: Category[] = [
  { id: 'cat1', name: 'Food', icon: 'pizza', color: 'hsl(var(--chart-1))' },
  { id: 'cat2', name: 'Transport', icon: 'bus', color: 'hsl(var(--chart-2))' },
  {
    id: 'cat3',
    name: 'Shopping',
    icon: 'shopping-bag',
    color: 'hsl(var(--chart-3))',
  },
  {
    id: 'cat4',
    name: 'Entertainment',
    icon: 'popcorn',
    color: 'hsl(var(--chart-4))',
  },
  { id: 'cat5', name: 'Bills', icon: 'file-text', color: 'hsl(var(--chart-5))' },
  {
    id: 'cat6',
    name: 'Health',
    icon: 'heart-pulse',
    color: 'hsl(var(--chart-1))',
  },
  { id: 'cat7', name: 'Salary', icon: 'briefcase', color: 'hsl(var(--chart-2))' },
];

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: 'txn1',
    title: 'Monthly Salary',
    amount: 150000,
    type: 'income',
    category: 'Salary',
    date: '2024-07-01T10:00:00Z',
    paymentMode: 'Card',
  },
  {
    id: 'txn2',
    title: 'Zomato Order',
    amount: 750.5,
    type: 'expense',
    category: 'Food',
    date: '2024-07-02T14:30:00Z',
    paymentMode: 'Card',
  },
  {
    id: 'txn3',
    title: 'Auto Rickshaw',
    amount: 125,
    type: 'expense',
    category: 'Transport',
    date: '2024-07-03T08:00:00Z',
    paymentMode: 'UPI',
  },
  {
    id: 'txn4',
    title: 'Movie Night',
    amount: 850,
    type: 'expense',
    category: 'Entertainment',
    date: '2024-07-05T20:00:00Z',
    paymentMode: 'Card',
  },
  {
    id: 'txn5',
    title: 'Electricity Bill',
    amount: 2500,
    type: 'expense',
    category: 'Bills',
    date: '2024-07-06T11:00:00Z',
    paymentMode: 'UPI',
  },
  {
    id: 'txn6',
    title: 'Lunch with Friends',
    amount: 1200,
    type: 'expense',
    category: 'Food',
    date: '2024-07-08T13:00:00Z',
    paymentMode: 'Cash',
  },
  {
    id: 'txn7',
    title: 'Myntra Shopping',
    amount: 3500,
    type: 'expense',
    category: 'Shopping',
    date: '2024-07-10T16:45:00Z',
    paymentMode: 'Card',
  },
  {
    id: 'txn8',
    title: 'Freelance Gig',
    amount: 25000,
    type: 'income',
    category: 'Salary',
    date: '2024-07-12T18:00:00Z',
    paymentMode: 'UPI',
  },
    {
    id: 'txn9',
    title: 'Pharmacy',
    amount: 550,
    type: 'expense',
    category: 'Health',
    date: '2024-07-15T09:20:00Z',
    paymentMode: 'Card',
  },
  {
    id: 'txn10',
    title: 'Internet Bill',
    amount: 1200,
    type: 'expense',
    category: 'Bills',
    date: '2024-06-15T10:00:00Z',
    paymentMode: 'UPI',
  },
];
